# Generated by Django 4.0.6 on 2022-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='match_date',
            field=models.CharField(max_length=20),
        ),
    ]
