# Generated by Django 4.0.6 on 2022-07-18 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='booking_date',
            field=models.DateTimeField(default=datetime.date(2022, 7, 18)),
        ),
    ]
