# Generated by Django 4.0.6 on 2022-07-18 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TPS_app', '0002_locations_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
