# Generated by Django 4.0.6 on 2022-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPS_app', '0003_alter_locations_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_capitan',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
